### ISSUE TITLE
How to convert a AAC Frame 22kHz Stereo to a WAV mono Buffer

### ISSUE THREAD

**Issue by stefc** [jimm98y/SharpJaad#1]
Really like your lib it seems it's exact what I need to read AAC audio track inside a M4A container and extract the WAV from it. 

I now seek for a solution to transform the stereo signal to a mono wav, did you have any idea how to archive this 

  // // Assuming 16-bit audio, each sample is 2 bytes
                        // // And each frame has 2 samples for stereo audio
                        // for (int i = 0; i < buf.Data.Length; i += 4)
                        // {
                        //     short left = BitConverter.ToInt16(buf.Data, i);
                        //     short right = BitConverter.ToInt16(buf.Data, i + 2);
                        //     short mono = (short)((left + right) / 2);

                        //     byte[] monoBytes = BitConverter.GetBytes(mono);
                        //     Array.Copy(monoBytes, 0, buf.Data, i, 2);
                        //     Array.Copy(monoBytes, 0, buf.Data, i + 2, 2);
                 }

something like the above code but without duplicate the signal to both channels and only have one channel signal

**Comment by jimm98y** [comment]
The library can give you PCM and from there it's up to you. You need to know how the PCM is formatted, how many bits are used per sample and how the stereo channel is muxed inside. These pieces of information are usually retrieved from the original file format. Once you know that, you can remove the bits/bytes you don't need and create a mono PCM that you can re-encode into some other format.

**Comment by stefc** [comment]
Also here I can join my current code on this topic. I solved it BinaryPrimitives to get rid of the endianness and than shuffle about the stereo signal and place it into the correct order for combine the stereo signal into mono in the correct manner I using Simd Operations so I can calculate 8 PCM Values at a time. For not allocating Arrays a lot I using the ArrayPool  

```c#
public static class BufferOperations
{
    private static int SimdLength = Vector<short>.Count;

    public static Memory<short> TransformEndianess(this Memory<short> frame) {
        var copy =  new Memory<short>(new short[frame.Length]);
        frame.CopyTo(copy);
         BinaryPrimitives.ReverseEndianness(frame.Span, copy.Span);
         return copy;
    }

    public static Memory<short> TransformStereoToMono(this Memory<short> frame)
    {
        ArrayPool<short> pool = ArrayPool<short>.Shared;
        for (int i = 0; i < frame.Length; i += SimdLength * 2)
        {
            var span = frame.Slice(i, SimdLength * 2).Span;

            var left = pool.Rent(SimdLength);
            var right = pool.Rent(SimdLength);

            for (int j = 0; j < SimdLength; j++)
            {
                left[j] = span[j * 2];
                right[j] = span[j * 2 + 1];
            }

            ((new Vector<short>(left) + new Vector<short>(right)) / 2).CopyTo(frame.Span.Slice(i / 2, SimdLength));

            pool.Return(left);
            pool.Return(right);
        }

        return frame[..(frame.Length / 2)]; // only first half of the memory is valid but will be reused 
    }
}
```
