### ISSUE TITLE
Decode AAC without  ADTSDemultiplexer

### ISSUE THREAD

**Issue by Vedan** [jimm98y/SharpJaad#7]
Hello.

How I can decode aac to wav without adts?

Regards,
Paul

**Comment by jimm98y** [comment]
To better understand how to use this without the ADTS header, you can take a look here: https://github.com/jimm98y/SharpRTSPtoWebRTC/blob/159427fddb79792b542061d8fd6af9d8a82b3ed8/src/SharpRTSPtoWebRTC/WebRTCProxy/RTSPtoWebRTCProxy.cs#L316
